# Generated by Django 5.2.8 on 2025-11-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/thumbs/'),
        ),
    ]
